on:
  workflow_dispatch:
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Install Docusaurus dependencies
    - name: Install Docusaurus dependencies
      run: npm install

    # Step 3: Build Docusaurus
    - name: Build Docusaurus
      run: npm run build

    # Step 4: Deploy to GitHub Pages
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        external_repository: qr-treasurehunt/qr-treasurehunt.github.io  # The GitHub Pages repository    
        publish_branch: master  # Push to the main branch of qr-treasurehunt.github.io
        publish_dir: build  # path to your Docusaurus build directory
